# Generated by Django 4.2.2 on 2023-06-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accountemailaddress_accountemailconfirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsBloter',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_bloter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsCwn',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_cwn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsItbiz',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_itbiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsItworld',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_itworld',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsRecentit',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_recentit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsTechworld',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_techworld',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=50)),
                ('related', models.CharField(max_length=158)),
            ],
            options={
                'db_table': 'related_keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalTKeywordsRemake',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'total_t_keywords_remake',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TotalKeyRelated',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
