# Generated by Django 4.2.2 on 2023-06-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_keywordsbloter_keywordscwn_keywordsitbiz_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='main_customuser',
        ),
    ]
