# Generated by Django 4.2.2 on 2023-06-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_totaltkeyrank_delete_maintechworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='career',
            field=models.CharField(choices=[('주니어', '신입 ~ 5년차'), ('시니어', '5년차 이상')], max_length=3, null=True, verbose_name='경력'),
        ),
    ]
