# Generated by Django 4.2.2 on 2023-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser_career_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='career_keyword',
            field=models.CharField(choices=[('AI', 'AI'), ('출시', '출시'), ('개발', '개발'), ('코딩', '코딩'), ('클라우드', '클라우드'), ('공개', '공개'), ('서비스', '서비스'), ('언어', '언어'), ('프로그래밍', '프로그래밍'), ('기반', '기반')], default=None, help_text='올해의 IT키워드 10개입니다! 관심 있는 항목에 체크해주세요!', max_length=100, null=True, verbose_name='관심 키워드'),
        ),
    ]
