# Generated by Django 4.2.2 on 2023-06-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
