# Generated by Django 4.2.2 on 2023-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_totalnewskt_alter_customuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsBloter',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_bloter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsCwn',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_cwn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsItbiz',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_itbiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsItworld',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_itworld',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsRecentit',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_recentit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsTechworld',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'keywords_techworld',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalKeyRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('related', models.CharField(max_length=158)),
            ],
            options={
                'db_table': 'total_key_related',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalTKeywordsRemake',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=50)),
                ('ranks', models.FloatField()),
            ],
            options={
                'db_table': 'total_t_keywords_remake',
                'managed': False,
            },
        ),
    ]
