# Generated by Django 4.2.2 on 2023-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_keywordsbloter_keywordscwn_keywordsitbiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=50)),
                ('related', models.CharField(max_length=158)),
            ],
            options={
                'db_table': 'related_keywords',
                'managed': False,
            },
        ),
    ]
