# Generated by Django 4.2.2 on 2023-06-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTechworldKT',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('news_date', models.CharField(max_length=50)),
                ('news_title', models.CharField(max_length=150)),
                ('news_text_sm', models.TextField()),
                ('url_in', models.CharField(max_length=124)),
                ('news_writer', models.CharField(max_length=50)),
                ('tags_string', models.CharField(blank=True, max_length=150, null=True)),
                ('thumb_addr', models.CharField(blank=True, max_length=228, null=True)),
                ('total_keywords', models.CharField(max_length=158)),
            ],
            options={
                'db_table': 'news_techworld_k_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalKeyRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('related', models.CharField(max_length=158)),
            ],
            options={
                'db_table': 'total_key_related',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalnewsKT',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('news_date', models.CharField(max_length=50)),
                ('news_title', models.CharField(max_length=164)),
                ('news_text_sm', models.TextField()),
                ('url_in', models.CharField(max_length=128)),
                ('news_writer', models.CharField(max_length=50)),
                ('tags_string', models.CharField(blank=True, max_length=188, null=True)),
                ('thumb_addr', models.CharField(blank=True, max_length=228, null=True)),
                ('total_keywords', models.CharField(max_length=188)),
            ],
            options={
                'db_table': 'totalnews_k_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalTKeyrank',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('keywords', models.CharField(max_length=100)),
                ('cnt', models.IntegerField()),
            ],
            options={
                'db_table': 'total_t_keyrank',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MainTechworld',
        ),
        migrations.DeleteModel(
            name='NewsTechworldT',
        ),
    ]
