# Generated by Django 4.2.2 on 2023-06-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_chart', '0002_newstechworldkt_totalkeyrelated_totalnewskt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
            ],
            options={
                'db_table': 'main_db',
                'managed': False,
            },
        ),
    ]
