# Generated by Django 4.2.2 on 2023-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accountemailaddress_accountemailconfirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalTKeyrank',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('keywords', models.CharField(max_length=100)),
                ('cnt', models.IntegerField()),
            ],
            options={
                'db_table': 'total_t_keyrank',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MainTechworld',
        ),
    ]
