# Generated by Django 4.2.2 on 2023-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSites',
            fields=[
                ('news_site', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('site_code', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'news_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalnewsKT',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('news_date', models.DateTimeField()),
                ('news_title', models.CharField(max_length=124)),
                ('news_text_sm', models.TextField()),
                ('url_in', models.CharField(max_length=128)),
                ('news_writer', models.CharField(max_length=50)),
                ('tags_string', models.CharField(blank=True, max_length=188, null=True)),
                ('thumb_addr', models.CharField(blank=True, max_length=228, null=True)),
                ('total_keywords', models.CharField(max_length=188)),
            ],
            options={
                'db_table': 'totalnews_k_t',
                'managed': False,
            },
        ),
    ]
