# Generated by Django 4.2.2 on 2023-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.CharField(max_length=20)),
                ('news_title', models.CharField(max_length=80)),
                ('news_text_sm', models.TextField()),
                ('url_in', models.URLField(max_length=100)),
                ('news_writer', models.CharField(max_length=20)),
                ('tags_string', models.CharField(max_length=150)),
                ('thumb_addr', models.CharField(max_length=100)),
                ('news_site', models.CharField(max_length=20)),
            ],
        ),
    ]
