# Generated by Django 4.2.2 on 2023-06-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_keywordsbloter_keywordscwn_keywordsitbiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
            ],
            options={
                'db_table': 'main_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsTechworldKT',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('news_date', models.CharField(max_length=50)),
                ('news_title', models.CharField(max_length=150)),
                ('news_text_sm', models.TextField()),
                ('url_in', models.CharField(max_length=124)),
                ('news_writer', models.CharField(max_length=50)),
                ('tags_string', models.CharField(blank=True, max_length=150, null=True)),
                ('thumb_addr', models.CharField(blank=True, max_length=228, null=True)),
                ('total_keywords', models.CharField(max_length=158)),
            ],
            options={
                'db_table': 'news_techworld_k_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=50)),
                ('related', models.CharField(max_length=158)),
            ],
            options={
                'db_table': 'related_keywords',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='NewsTechworldT',
        ),
        migrations.DeleteModel(
            name='TotalKeyRelated',
        ),
    ]
